---
title: "Lobster Report"
format: html
authors: "Rachel de Sobrino, Raven Dawson"
bibliography: references.bib
---

## Data

Data on abundance, size and fishing pressure of California spiny lobster (Panulirus interruptus) are collected along the mainland coast of the Santa Barbara Channel. Spiny lobsters are an important predator in giant kelp forests off southern California. [@lter2022]

```{r}
#| echo: false
#| warning: false
library(dplyr)
library(ggplot2)
```

## When and where are lobsters found?
```{r}
lobster_clean <- lobster_abundance %>% 
  mutate(SIZE_MM = na_if(SIZE_MM, -99999))

lobster_summarize <- lobster_clean %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n()) ## what's this?? 

ggplot(data = lobster_summarize, aes(x = YEAR, y=COUNT, color=SITE)) + 
  geom_line() +
  geom_point()
ggsave("../figs/v1.png")
```
## How big are the lobsters?
```{r}
ggplot(data=lobster_size_lrg, aes(x=SIZE_BIN, y = COUNT)) +
  geom_col(aes(fill=SIZE_BIN)) +
  labs(title = "Sizes of Lobsters", x = "Size", y = "Count") +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "green"))

  ggsave("../figs/v2.png")
```

