---
title: "Owner Analysis"
format: html
author: "Rachel de Sobrino"
---

## Exercise: Explore, Clean, and Wrangle Data
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```

```{r}
lobster_abundance <- read_csv("../data/Lobster_Abundance_All_Years_20220829.csv")
head(lobster_abundance)
```
```{r}
lobster_clean <- lobster_abundance %>% 
  mutate(SIZE_MM = na_if(SIZE_MM, -99999))

head(lobster_clean)
```
```{r}
lobster_no_napl <- lobster_abundance %>% 
  filter(SITE != "NAPL")
head(lobster_no_napl)
```

```{r}
lobster_big_AQUE <- lobster_clean %>% 
  filter(SITE == "AQUE" & SIZE_MM > 70)

head(lobster_big_AQUE)
```
```{r}
max(lobster_abundance$SIZE_MM)
max(lobster_abundance$SIZE_MM, na.rm = TRUE)

lobster_size_mon <- lobster_clean %>% 
  group_by(SITE, MONTH) %>% 
  summarize(MAX_LENGTH = max(SIZE_MM, na.rm = TRUE))

head(lobster_size_mon)
```
## Exercise Data Visualization
```{r}
ggplot(lobster_clean, aes(x = SIZE_MM )) +
  geom_histogram() + facet_wrap(vars(SITE)) 
```
```{r}
lobster_summarize <- lobster_clean %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n()) ## what's this?? 

head(lobster_summarize)
```
```{r}
ggplot(data = lobster_summarize, aes(x = YEAR, y=COUNT, color=SITE)) + 
  geom_line() +
  geom_point()
ggsave("../figs/v1.png")
```
```{r}
lobster_size_lrg <- lobster_clean %>% 
  filter(YEAR %in% c("2019", "2020", "2021")) %>% 
  mutate(SIZE_BIN = if_else(SIZE_MM <= 70, "SMALL", "LARGE")) %>% 
  group_by(SIZE_BIN) %>% 
  summarize(COUNT = n()) %>% 
  drop_na()
lobster_size_lrg
```
```{r}
ggplot(data=lobster_size_lrg, aes(x=SIZE_BIN, y = COUNT)) +
  geom_col(aes(fill=SIZE_BIN)) +
  labs(title = "Sizes of Lobsters", x = "Size", y = "Count") +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "green"))

  ggsave("../figs/v2.png")
```


